### PR TITLE
File added for training

### PR DESCRIPTION
**Pull request by puji10**
my changes are ready to be merged to main branch. Please review..

### CODE REVIEW

**Review by Olataydevops — APPROVED** [review]
Change  approved.

**Review by nganjelucy — APPROVED** [review]

**Review by Orisumbi — APPROVED** [review]
Well done

**Review by HandsOnDevOpsTraining — APPROVED** [review]

**Comment by Davidukre** [comment]
Approved

**Review by Olataydevops — COMMENTED** [review]
Good job!

**Pull request merged**
