### PR TITLE
Please review chnages are ready to be merge

### PR DESCRIPTION
**Pull request by Davidukre**
These are the changes made please review

### CODE REVIEW

**Review by nganjelucy — APPROVED** [review]
looks good

**Comment by Davidukre** [comment]
@ifyEze83 Please approve

**Comment by Davidukre** [comment]
@pbodedeyi and @ifyEze83 Please approve

**Comment by Davidukre** [comment]
@shaistafaisal28 Please review

**Comment by Davidukre** [comment]
@HandsOnDevOpsTraining please review

**Review by pbodedeyi — APPROVED** [review]
good

**Pull request merged**
